- name: clone nginx-proxy repo
  git: repo=https://github.com/jwilder/nginx-proxy.git
       dest=/home/{{ local_username.stdout }}/tools/nginx-proxy

- name: create custom nginx configuration
  copy: src=my_proxy.conf dest=/home/{{ local_username.stdout }}/tools/nginx-proxy/my_proxy.conf

- name: build loadbalancer image
  command: docker build -t loadbalancer /home/{{ local_username.stdout }}/tools/nginx-proxy

- name: create loadbalancer container
  docker:
    name: loadbalancer
    image: loadbalancer:latest
    state: started
    ports:
    - "80:80"
    volumes:
    - /home/{{ local_username.stdout }}/tools/nginx-proxy/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    - /var/run/docker.sock:/tmp/docker.sock
