---
- name: install packages
  yum: name={{ item }} state=installed
  with_items:
    - nginx
    - php-fpm
    - php-mysqlnd

- name: set up nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx 

- name: enable nginx and php-fpm
  service: name={{ item }} state=started enabled=yes
  with_items:
    - nginx
    - php-fpm
